### ISSUE TITLE
update function is not working

### ISSUE THREAD

**Issue by miheico** [Mi-Walkie-Talkie-by-Darkhorse/Mi-Walkie-Talkie-Plus#6]
I am not able to update any firmware files, no matter if it modified or original. I have XXMDJJ02 radio and I was using android 11 and android 9 smartphones. I have tried Mi PTT+ 2.13.7 and 2.9.34  and non didn't work. 
All stops at those windows:
![image](https://user-images.githubusercontent.com/62471190/164559786-7dca4e92-2794-4cd2-a4e0-53e2e4a28e42.png)

**Comment by miheico** [comment]
Any idea how to make it work?

**Comment by Mi-Walkie-Talkie-by-Darkhorse** [comment]
> Any idea how to make it work?
>
It turned out that there are several hardware versions of XXMDJJ02 radio exist. It is not a surprise - all the previous Mi Walkie-talkie models have several hardware versions. The problem is, nowaday I only have the firmware for hardware version 4.8, while you have the hardware version 4.5, according to the screenshot. 
Further discussions are in the XMDJJ02-firmware project: https://github.com/Mi-Walkie-Talkie-by-Darkhorse/Mi2-XMDJJ02-firmware/issues/1
